@startuml
title:"Poser une Bombe"

participant perso
participant listeBombe


->perso:poserBombe()
activate perso
perso-> listeBombe:size()
activate listeBombe
perso <-- listeBombe:tailleListeDeBombe
deactivate listeBombe
alt tailleListeDeBombe < 3
perso -> Bombe :new bombe(perso.getX,perso.getY);
activate Bombe
Bombe-->perso:listeBombe++
deactivate Bombe
end
<-- perso
deactivate perso


@enduml