@startuml
participant "main" as main
participant "labyJ: Labyjeu" as labyJ
participant "b : Bombe" as b
main ->labyJ:poserbombe()
activate labyJ
labyJ->b : aExploser()
activate b
b-->labyJ : supprimer bombe
deactivate b
labyJ -->main
deactivate labyJ
@enduml