@startuml

title Considérer le monstre dans les déplacements du personnage
participant "laby:Labyrinthe" as laby
participant "m:Monstre" as m
participant "p:Perso" as p
-> laby :deplacerPerso(String action)
activate laby
        laby -> m : getX()
        activate m
        laby <-- m
        deactivate m
        laby -> m : getY()
        activate m
        laby <-- m
        deactivate m
      alt presense d'un monstre
      else
        laby -> p : getX()
                activate p
                laby <-- p
                deactivate p
                laby -> p : getY()
                activate p
                laby <-- p
                deactivate p
      end
 <-- laby
deactivate laby


@enduml