@startuml

title attaque d'un monstre
participant "laby:Labyrinthe" as laby
participant "p:Perso" as perso
participant "m:Monstre" as m
-> laby : deplacerEntite(String action)
activate laby
        laby -> laby : etreColler() : bColler
      alt bColler = true
           laby -> perso : setVie(-1)
           activate perso
           perso --> laby
           deactivate perso
      else bColler = false
            laby -> m : setX()
            activate m
            laby <-- m
            deactivate m
            laby -> m : setY()
            activate m
            laby <-- m
            deactivate m

      end
  <-- laby
deactivate laby


@enduml