@startuml
title:"Recupérer amulette"

participant labyrinthe
participant personnage
participant amulette


->labyrinthe:deplacerEntite(Direction d)
activate labyrinthe

labyrinthe->amulette:etrePresent(int dxg,int dyg)

activate amulette
labyrinthe<--amulette:boolean
deactivate amulette
alt boolean=true
labyrinthe->personnage:amuletteTrouve = true
activate personnage
labyrinthe<--personnage:amulette.getX() = perso.getX()
labyrinthe<--personnage:amulette.getY() = perso.getY()
deactivate personnage
end
<--labyrinthe
deactivate labyrinthe
@enduml
